# Generated by Django 3.1.3 on 2020-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201202_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumnail_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
