# Generated by Django 3.1.3 on 2020-12-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_thumnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='store.enquiry'),
        ),
    ]
