# Generated by Django 3.1.3 on 2020-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201203_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=100)),
                ('auth_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'phone_auths',
            },
        ),
    ]
